export const dashConstants = {
  RENDER_HOME: 'RENDER_HOME',
  RENDER_ASSIGN: 'RENDER_ASSIGN',
  RENDER_EDIT: 'RENDER_EDIT',
  RENDER_DELETE: 'RENDER_DELETE',
  RENDER_VIEW: 'RENDER_VIEW',
  RENDER_AUTHORIZE: 'RENDER_AUTHORIZE'
};
