export const userConstants = {
  REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'USER_REGISTER_FAILURE',

  LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USER_LOGIN_FAILURE',

  VERIFY_REQUEST: 'USER_VERIFY_REQUEST',
  VERIFY_SUCCESS: 'USER_VERIFY_SUCCESS',
  VERIFY_FAILURE: 'USER_VERIFY_FAILURE',

  LOGOUT: 'USER_LOGOUT',

  CLEAR_ERRORS: 'CLEAR_LOGIN_ERRORS',

  SET_REVIEW: 'SET_LTIERATURE_REVIEW',
  CLEAR_REVIEW: 'CLEAR_LITERATURE_REVIEW',

  UPDATE_PATH: 'UPDATE_PREVIOUS_PATH'
};
